### ISSUE TITLE
Show participants online in bridge channel names

### ISSUE THREAD

**Issue by ledlamp** [ledlamp/discord-mpp-bridge#12]

**Comment by Vistril** [comment]
wait, you mean like #bridge-title (participant count) ?

**Comment by ledlamp** [comment]
Something like `# (20)-lobby` using whatever unicode char is similar to parenthesis

**Comment by Vistril** [comment]
oh ok

**Comment by ledlamp** [comment]
![image](https://user-images.githubusercontent.com/24686877/45002821-d09e0080-af8f-11e8-84c7-628111abe45f.png)

**Comment by Vistril** [comment]
oof

**Comment by ledlamp** [comment]
![image](https://user-images.githubusercontent.com/24686877/45002831-0f33bb00-af90-11e8-9266-f7ae4cdbc9e5.png)

**Comment by Vistril** [comment]
guess that works

**Comment by ledlamp** [comment]
meh, nah
