### ISSUE TITLE
Make MPP Client Disconnect from a room after 5 minutes after there aren't any chat messages from that channel.

### ISSUE THREAD

**Issue by BopItFreak** [ledlamp/discord-mpp-bridge#16]
Make MPP Client Disconnect from a room after 5 minutes after there aren't any chat messages from that channel. If the MPP client stays connected, it's just Room spam. If someone on discord sends a message in that linked channel, the MPP client will connect again. We can't make it if no one comes to the room in 5 minutes, as JPDLD or Omegabot will come in it.

**Comment by ledlamp** [comment]
This has already been resolved with #5. The channel is made hidden when nobody else is in it.
Lobby channels cannot be hidden, but unnecessary lobby channels will be pruned during maintenance.
